name: party
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:

  flutter_localizations: 
    sdk: flutter
  localization: ^2.0.0+1

  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  ionicons: ^0.1.2
  carousel_pro: ^1.0.0
  animate_do: ^2.0.0
  flutter_advanced_drawer: ^1.2.3+1
  iconsax: ^0.0.8
  bottom_bar: ^1.2.5
  image_picker: ^0.8.4+11
  image_cropper: ^1.4.1
  intl: ^0.17.0
  shimmer: ^2.0.0
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  firebase_storage: ^10.0.3
  cloud_firestore: ^3.1.10
  flutter_spinkit: ^5.1.0
  http: ^0.13.4
  carousel_slider: ^4.0.0
  flutterfire_ui: ^0.3.5+1
  cached_network_image: ^3.2.0
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  flutter_config: ^2.0.0
  geocoding: ^2.0.4
  url_launcher: ^6.0.20
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  
  uses-material-design: true
  
  assets:
    - lib/i18n/
    - images/partyAppBar.jpg
    - images/partyBackground.jpg
    - images/partyBackground1.jpg
    - images/partyOnly.png
    - images/partySplash.png
    - images/partyEscritoLogo.png
    - images/spain.png
    - images/usa.png
    - images/brasil.jpg
    - images/mark.png
    - images/party_coins.png
    - images/party_coins_20.png
    - images/party_coins_10.png
    - images/party_coins_5.png

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
